<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <!-- LangVersion>latest</LangVersion !-->
    <IsPackable>false</IsPackable>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="FsUnit.fs" />
    <Compile Include="PropertySpecs.fs" />
    <Compile Include="SlidePropertySpecs.fs" />
    <Compile Include="SectionsSpecs.fs" />
    <Compile Include="SpeakerNotesSpecs.fs" />
    <Compile Include="FsRevealIntroTest.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Index.md">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FsReveal\FsReveal.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="8.0.100" />
    <PackageReference Include="FSharp.Compiler.Service" Version="43.8.100" />
    <PackageReference Include="FSharp.Formatting" Version="20.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
  </ItemGroup>
</Project>