<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="FsUnit.fs" />
    <Compile Include="PropertySpecs.fs" />
    <Compile Include="SlidePropertySpecs.fs" />
    <Compile Include="SectionsSpecs.fs" />
    <Compile Include="SpeakerNotesSpecs.fs" />
    <Compile Include="Program.fs" />
    <Compile Include="FsRevealIntroTest.fs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="paket.references" />
    <Content Include="Index.md">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="NUnit" Version="4.2.2" />
    <PackageReference Include="NUnit.Analyzers" Version="4.4.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>