<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;netstandard2.0</TargetFrameworks>
    <DefineConstants>$(DefineConstants);DOTNETCORE</DefineConstants>
    <AssemblyName>Fake.Core.String</AssemblyName>
    <OutputType>Library</OutputType>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="String.fs" />
    <Compile Include="StringBuilder.fs" />
  </ItemGroup>
  <PropertyGroup>
    <DefineConstants>$(DefineConstants);NETSTANDARD1_5</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DefineConstants>$(DefineConstants);RELEASE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="8.0.100" />
    <PackageReference Include="FSharp.Compiler.Service" Version="43.8.100" />
  </ItemGroup>
</Project>
